### ISSUE TITLE
Реализация класса Session

### ISSUE THREAD

**Issue by tam2511** [tam2511/SelfFlyingEngine#5]

**Comment by purple63** [comment]
![architecture-ver-2-0](https://github.com/tam2511/SelfFlyingEngine/assets/142740463/ae2dc963-dfbe-41d6-953f-c977b6b9dfe9)

**Comment by purple63** [comment]
![architecture-ver-2-1](https://github.com/tam2511/SelfFlyingEngine/assets/142740463/6d453890-06c5-4b2e-aef1-6a275a045188)
